version: "3.9"

services:
  # 🔹 GATEWAY (центральный вход для юзеров)
  gateway:
    image: nginx:alpine
    container_name: gateway
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro   # наш прокси конфиг
      - ./certs:/etc/nginx/certs:ro                    # SSL
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - legacy-api
      - new-api
      - frontend
    networks:
      - frontend-net
      - backend-net

  # 🔹 LEGACY SYSTEM (PHP7.4 + Symfony3.4 + встроенный фронтенд)
  legacy-api:
    build:
      context: ./legacy-api
      dockerfile: Dockerfile
    container_name: legacy-api
    environment:
      - APP_ENV=prod
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=app
      - DB_USER=app
      - DB_PASSWORD=secret
      - REDIS_HOST=redis-legacy
    depends_on:
      - mariadb
      - redis-legacy
    networks:
      - backend-net

  # 🔹 NEW API (PHP8.4 + Symfony + API Platform)
  new-api:
    build:
      context: ./new-api
      dockerfile: Dockerfile
    container_name: new-api
    environment:
      - APP_ENV=prod
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=app
      - DB_USER=app
      - DB_PASSWORD=secret
      - REDIS_HOST=redis-new
      - RABBITMQ_HOST=rabbitmq
      - KEYCLOAK_URL=http://keycloak:8080
    depends_on:
      - mariadb
      - redis-new
      - rabbitmq
    networks:
      - backend-net

  # 🔹 NEW FRONTEND (React SPA → статика в nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - frontend-net

  # 🔹 DATABASE (MariaDB)
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend-net

  # 🔹 REDIS (Legacy)
  redis-legacy:
    image: redis:7-alpine
    container_name: redis-legacy
    command: redis-server --appendonly yes
    volumes:
      - redis_legacy_data:/data
    networks:
      - backend-net

  # 🔹 REDIS (New API)
  redis-new:
    image: redis:7-alpine
    container_name: redis-new
    command: redis-server --appendonly yes
    volumes:
      - redis_new_data:/data
    networks:
      - backend-net

  # 🔹 RABBITMQ (для асинхронных задач нового API)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672" # mgmt UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend-net

  # 🔹 KEYCLOAK (SSO сервис)
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    ports:
      - "8081:8080"
    networks:
      - backend-net

# 🔹 VOLUMES (для хранения данных)
volumes:
  db_data:
  redis_legacy_data:
  redis_new_data:
  rabbitmq_data:

# 🔹 NETWORKS
networks:
  backend-net:
  frontend-net: